### ISSUE TITLE
Scroll para hacer clic a un elemento

### ISSUE THREAD

**Issue by anampardo** [a0/a0-webdrone-ruby#5]
Aldrin, Hola,

He estado haciendo uso del sistema webdrone para realizar las pruebas de UI de mi sistema, pero encontré una dificultad cuando quiero hacer clic a un elemento que no se muestra en el espacio activo del browser.

Actualmente mi vista tiene un topbar fixed, es decir que no se oculta al hacer scroll down. Cuando utilizo la sentencia: a0.clic.xpath '[path]'; el sistema hace scroll down hasta el elemento y lo deja debajo del topbar por lo que no puede hacerle clic.

Existe alguna manera de hacer el scroll de manera controlada? o alguna otra manera de atacar esta acción?

Muchas gracias.

**Comment by aldrinmartoq** [comment]
Hola Ana, fantástico que uses Webdrone.

Webdrone está basado en selenium, luego el que hace el scroll es la combinación selenium/navegador. Como a priori no sé cómo podemos cambiar lo que pides, podrías intentar hacer scroll "manualmente" antes de pinchar tu elemento.

Si tu sitio usa jQuery, es fácil hacer scroll de la ventana digamos 500 px; si no usas jQuery también lo puedes hacer con javascript nativo y ejecutar ese javascript con Webdrone antes de pinchar el elemento. Entonces te quedaría algo así:

``` ruby
a0.exec.script   '$(window).scrollTop(500);'
a0.clic.xpath    '[path]'

```

Te dejo de ejercicio encontrar la posición del elemento que buscas con javascript para centrarlo correctamente. Si lo resuelves en javascript nativo, mándalo en este ticket así lo agregamos como parte de Webdrone. Hay varias cosas que Webdrone las resuelve vía javascript.

**Comment by anampardo** [comment]
Aldrin, 

Tu solución funciona. El único problema de hacer scroll manual a la pantalla es que si las pruebas se ejecutan en un pc con resolución distinta, quizás las pruebas dejarían de funcionar y daría un falso negativo sobre el caso.

Sobre tu segunda solución, estaba justo intentando eso y llegamos a esto:

```
a0.exec.script 'document.querySelector(".class1").click();'
a0.exec.script 'document.getElementById("elementId").click();'
```

De esta manera podemos hacer click a los objetos sin que se mueva la pantalla y sin necesidad de hacer scroll. Lo manejamos con javascript nativo porque no nos dimos cuenta que podríamos usar jQuery :$, pero la lógica sería la misma.

**Comment by aldrinmartoq** [comment]
Encontré la manera de hacerlo con Javascript nativo, con Webdrone sería algo del siguiente estilo:

```ruby
elem = a0.find.on 'algo'
a0.exec.script 'arguments[0].scrollIntoview()', elem
```

En una próxima versión agregaré algún parámetro (ej: `scroll: true`) de manera que Webdrone haga todo el trabajo, por ejemplo:

```ruby
# hace scroll hasta dejarlo visible, lo marca, saca un screenshot y luego hace clic
a0.clic.on 'algo', scroll: true, mark: on, shot: true
```

**Comment by aldrinmartoq** [comment]
Agregué una versión inicial de scroll: true, y funciona. Puede ocurrir que a veces el elemento no se vea (esté tapado por otro elemento), pero eso ya es harina de otro costal. Slds,
