### ISSUE TITLE
Firefox 47+ breaks compatibility with webdrone

### ISSUE THREAD

**Issue by jrovegno** [a0/a0-webdrone-ruby#7]
Os:Windows
Last working version: https://github.com/a0/a0-webdrone-ruby/wiki/Installation

**Comment by aldrinmartoq** [comment]
My recomendation is to stay in old versions of Firefox <=46… Firefox's marionette [is not finished](https://github.com/mozilla/geckodriver#supported-firefoxen)

> Marionette and geckodriver are not yet feature complete. This means it does not yet offer full conformance with the WebDriver standard or complete compatibility with Selenium.

Is it working for you, @jrovegno?

**Comment by jrovegno** [comment]
@aldrinmartoq Firefox <=46 , webdrone , selenium-webdriver:2.53.4 (works ok)

In Firefox >=47 , webdrone, selenium-webdriver:3.0.1 , geckodriver-v0.11.1 (i get a profile error) SeleniumHQ/selenium/issues/2933

**Comment by aldrinmartoq** [comment]
It seems to be working now, please upgrade and try again with:

- Latest Webdrone gem: `gem install webdrone` current version is 1.6.0
- Latest selenium-webdriver gem: `gem install selenium-webdriver` current version is 3.0.5
- Latest [Firefox](https://www.mozilla.org/en-US/firefox/all/) current version is 50.1.0
- Latest [Geckodriver](https://github.com/mozilla/geckodriver/releases), currently 0.13.0

**Comment by aldrinmartoq** [comment]
Everything seems to be working using [Firefox](https://www.mozilla.org/en-US/firefox/all/) 55 and [Geckodriver](https://github.com/mozilla/geckodriver/releases) 0.18.0.

I'm closing this bug.
